query { repository(owner: "mezivillager", name: "hacer") { main: ref(qualifiedName: "refs/heads/main") { target { ... on Commit { oid statusCheckRollup { contexts(first: 50) { nodes { ... on CheckRun { databaseId name conclusion completedAt detailsUrl annotations(first: 50) { nodes { message } } } } } } } } } pullRequests(states: OPEN, first: 100) { nodes { number commits(last: 1) { nodes { commit { oid statusCheckRollup { contexts(first: 50) { nodes { ... on CheckRun { databaseId name conclusion completedAt detailsUrl annotations(first: 50) { nodes { message } } } } } } } } } } } } }
