import { describe, it, expect } from 'vitest'
import {
  ALLOWED_TILDE_ROOTS,
  OPT_OUT_MARKER,
  findAbsolutePaths,
  formatViolations,
  isScannedFile,
} from './docPaths.logic.mjs'

describe('isScannedFile', () => {
  it('scans markdown under docs/', () => {
    expect(isScannedFile('docs/plans/2026-06-19-thing.md')).toBe(true)
  })

  it('scans top-level agent entry docs', () => {
    expect(isScannedFile('AGENTS.md')).toBe(true)
    expect(isScannedFile('CLAUDE.md')).toBe(true)
    expect(isScannedFile('REPO_MAP.md')).toBe(true)
  })

  it('ignores vendored .cursor/ tooling content', () => {
    expect(isScannedFile('.cursor/rules/020-git-worktree-no-main.mdc')).toBe(false)
  })

  it('ignores non-markdown files', () => {
    expect(isScannedFile('src/store/circuitStore.ts')).toBe(false)
    expect(isScannedFile('scripts/check-doc-paths.mjs')).toBe(false)
  })

  it('ignores CHANGELOG.md because it is generated by semantic-release', () => {
    expect(isScannedFile('CHANGELOG.md')).toBe(false)
  })

  it('ignores vendored superpowers skills, which sync-superpowers.sh overwrites', () => {
    expect(isScannedFile('.claude/skills/systematic-debugging/CREATION-LOG.md')).toBe(false)
    expect(isScannedFile('.claude/skills/using-git-worktrees/SKILL.md')).toBe(false)
  })

  it('still scans the two skills the sync explicitly preserves', () => {
    expect(isScannedFile('.claude/skills/hacer-patterns/SKILL.md')).toBe(true)
    expect(isScannedFile('.claude/skills/docs-sync/SKILL.md')).toBe(true)
  })

  it('ignores node_modules and the sync temp dir', () => {
    expect(isScannedFile('node_modules/foo/README.md')).toBe(false)
    expect(isScannedFile('.tmp_superpowers/skills/x/SKILL.md')).toBe(false)
  })
})

describe('findAbsolutePaths', () => {
  it('returns nothing for a clean doc', () => {
    expect(findAbsolutePaths('See `src/simulation/topologicalEval.ts` for details.')).toEqual([])
  })

  it('flags a macOS home path', () => {
    const v = findAbsolutePaths('cd /Users/villager/Documents/codelab/ha/hacer')
    expect(v).toHaveLength(1)
    expect(v[0]).toMatchObject({ line: 1, match: '/Users/villager/Documents/codelab/ha/hacer' })
  })

  it('flags a Linux home path', () => {
    expect(findAbsolutePaths('run from /home/user/my-app')).toHaveLength(1)
  })

  it('flags a /root path', () => {
    expect(findAbsolutePaths('cd /root/project')).toHaveLength(1)
  })

  it('flags a Windows drive path', () => {
    expect(findAbsolutePaths('open C:\\Users\\dev\\repo')).toHaveLength(1)
  })

  it('flags a machine-specific tilde path', () => {
    const v = findAbsolutePaths('- ref: `~/Documents/codelab/ha/web-ide/simulator/src/x.ts`')
    expect(v).toHaveLength(1)
    expect(v[0].match).toBe('~/Documents/codelab/ha/web-ide/simulator/src/x.ts')
  })

  it.each(ALLOWED_TILDE_ROOTS)('allows the portable tilde root ~/%s', (root) => {
    expect(findAbsolutePaths(`hooks live in \`~/${root}/hooks/\``)).toEqual([])
  })

  it('reports the 1-based line number of each violation', () => {
    const v = findAbsolutePaths(['clean line', '', 'cd /Users/villager/x'].join('\n'))
    expect(v).toHaveLength(1)
    expect(v[0].line).toBe(3)
  })

  it('reports every violation on a multi-line doc', () => {
    const v = findAbsolutePaths(['cd /Users/a/x', 'then /home/b/y'].join('\n'))
    expect(v.map((x) => x.line)).toEqual([1, 2])
  })

  it('does not flag a URL that merely contains /home/', () => {
    expect(findAbsolutePaths('see https://example.com/home/docs for more')).toEqual([])
  })

  it('does not flag repo-relative paths', () => {
    expect(findAbsolutePaths('see ../web-ide/simulator/src/chip/chip.ts')).toEqual([])
    expect(findAbsolutePaths('see docs/roadmap/vision.md')).toEqual([])
  })

  it('does not flag a bare /home or /Users mention with no segment after it', () => {
    expect(findAbsolutePaths('the /home directory')).toEqual([])
  })

  it(`skips any line carrying the ${OPT_OUT_MARKER} marker`, () => {
    const text = `cd /Users/villager/x <!-- ${OPT_OUT_MARKER} -->`
    expect(findAbsolutePaths(text)).toEqual([])
  })

  it('only opts out the marked line, not the whole file', () => {
    const text = [`cd /Users/a/x <!-- ${OPT_OUT_MARKER} -->`, 'cd /Users/b/y'].join('\n')
    const v = findAbsolutePaths(text)
    expect(v).toHaveLength(1)
    expect(v[0].line).toBe(2)
  })

  it('handles empty and missing input', () => {
    expect(findAbsolutePaths('')).toEqual([])
    expect(findAbsolutePaths(undefined)).toEqual([])
  })
})

describe('formatViolations', () => {
  it('renders file:line:match so editors can jump to it', () => {
    const out = formatViolations('docs/a.md', [{ line: 3, column: 4, match: '/Users/x/y' }])
    expect(out).toContain('docs/a.md:3')
    expect(out).toContain('/Users/x/y')
  })

  it('renders nothing for no violations', () => {
    expect(formatViolations('docs/a.md', [])).toBe('')
  })
})
